FROM python

#install environment dependencies
RUN apt-get update -yqq && apt-get install -yqq --no-install-recommends netcat-traditional && apt-get -q clean


#set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

#add requirements
COPY ./requirement.txt /usr/src/app/requirements.txt

#install requirements
RUN pip install -r requirements.txt

#add entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh

#add app
COPY . /usr/src/app

#run server
CMD ["./entrypoint.sh"]

CMD python manage.py run -h 0.0.0.0